---
# application configuration

# requires login
login: false

# application prompt, used to set the context
prompt:
  text: You are an helpful digital avatar

# language, e.g. it-IT, de-DE, es-Es
language: en-GB

# LLM provider
llm:
  chat: openai/gpt-4o-mini
  tools: openai/gpt-4o-mini
  sentiment: openai/gpt-4o-mini
  tasks: openai/gpt-4o-mini
  intent: openai/gpt-4o-mini
  translation: openai/gpt-4o-mini