---
# application configuration

# requires login
login: false

# id of the default avatar
avatar: anna

# background for the avatar
background: milkyway

# language of the avatar
language: en-GB

# LLM provider
llm:
  chat: openai/gpt-4o
  tools: openai/gpt-4o
  sentiment: openai/gpt-4o-mini
  tasks: openai/gpt-4o-mini
  intent: openai/gpt-4o
  translation: openai/gpt-4o-mini

# default avatar prompt
prompt:
  text: >-
    You are a friendly assistant in charge of helping users getting started with the SERMAS project.
